# Generated by Django 4.2 on 2023-04-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.TextField(max_length=200)),
                ('tempo_preparacao', models.IntegerField()),
                ('serve_pessoas', models.IntegerField()),
                ('serve_porcoes', models.CharField(max_length=60)),
                ('publicada', models.BooleanField(default=False)),
                ('imagem', models.ImageField(upload_to='imagens')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
