# Generated by Django 4.2 on 2023-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank='True', upload_to='imagens'),
        ),
    ]
