# Generated by Django 4.2 on 2023-04-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_alter_receita_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens'),
        ),
    ]
